# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpoppler-cpp-dev libtesseract-dev libleptonica-dev tesseract-ocr-eng
before_deploy: Rscript -e 'install.packages("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
after_success:
  - Rscript -e 'covr::codecov()'
